# Generated by Django 6.0.4 on 2026-04-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
